spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  base-url: ${APP_BASE_URL:http://localhost:8080/chronoMind}
  env: ${APP_ENV:Local}

server:
  servlet:
    context-path: /chronoMind

springdoc:
  swagger-ui:
    path: /docs


jwt:
  secret: ${JWT_SECRET}